@DaprOneService.API_HostAddress = http://localhost:5015


### Create User and Publish UserCreatedEvent
POST {{DaprOneService.API_HostAddress}}/users
Content-Type: application/json

{
  "userName": "John Doe",
  "email": "john.doe@example.com"
}

###
